export const HITTING_STATS = {
  OPS: 'OnBasePlusSlugging',
  AVG: 'BattingAverage',
  HR: 'HomeRuns',
  RBI: 'RunsBattedIn',
  R: 'Runs',
  H: 'Hits',
  '2B': 'Doubles',
  '3B': 'Triples',
  G: 'Games',
  AB: 'AtBats',
  BB: 'Walks',
  SO: 'Strikeouts',
  SB: 'StolenBases',
  CS: 'CaughtStealing',
  OBP: 'OnBasePercentage',
  SLG: 'SluggingPercentage',
}

export const PITCHING_STATS = {
  W: 'Wins',
  L: 'Losses',
  ERA: 'EarnedRunAverage',
  G: 'Games',
  SHO: 'PitchingShutOuts',
  SV: 'Saves',
  SVB: 'PitchingBlownSaves',
  IP: 'InningsPitchedDecimal',
  H: 'PitchingHits',
  R: 'PitchingRuns',
  ER: 'PitchingEarnedRuns',
  HR: 'PitchingHomeRuns',
  HB: 'PitchingHitByPitch',
  BB: 'PitchingWalks',
  SO: 'PitchingStrikeouts',
  WHIP: 'WalksHitsPerInningsPitched',
  AVG: 'PitchingBattingAverageAgainst',
}
